/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_DNSPolicy = map[string]string{
	"":     "DNSPolicy describes what domains are allowed to be resolved by a set of Pods",
	"spec": "Specification of the desired behavior for this DNSPolicy.",
}

func (DNSPolicy) SwaggerDoc() map[string]string {
	return map_DNSPolicy
}

var map_DNSPolicyList = map[string]string{
	"":      "DNSPolicyList is a list of DNSPolicy objects.",
	"items": "items is a list of DNSPolicy objects.",
}

func (DNSPolicyList) SwaggerDoc() map[string]string {
	return map_DNSPolicyList
}

var map_DNSPolicySpec = map[string]string{
	"":               "DNSPolicySpec provides specification for a DNSPolicy",
	"podSelector":    "podSelector selects pods to which this DNSPolicy object applies. Any pod selected by this policy will only be allowed to resolve domains in the allowedDomains list. Enforcement of this policy against a pod means that the pod can only resolve domains in allowedDomains.\n\nAn empty podSelector means that this policy should apply to all pods in the namespace. Host network pods are excluded from this policy.",
	"allowedDomains": "allowedDomains is a list of domains that are resolvable for pods selected by podSelector. Only fully qualified domain names (e.g. www.example.com) and wildcard subdomains (e.g. *.example.com) are supported. Wildcards are only allowed on the left-most parts of the domain, so *.*.example.com is allowed, but example.* is not. Matching domains must have the same number of parts, so foo.bar.example.com does not match for *.example.com.",
}

func (DNSPolicySpec) SwaggerDoc() map[string]string {
	return map_DNSPolicySpec
}

// AUTO-GENERATED FUNCTIONS END HERE
